config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get '/about', to: 'pages#about'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
 has_many :comments, dependent: :destroy
 has_attached_file :image, styles: {large: "600x600>",medium: "300x300>", thumb: "150x150#"  }
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
 validates :title, presence: true, length: {minimum:5}
 # validates :comments , presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :exception

 def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
 helper_method :current_user

 def authorize
   redirect_to '/login' unless current_user
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name,:body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authorize
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 3) 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
      if @post.save
       redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %></p>
  </div>
  <p><%= link_to 'Delete', [comment.post, comment],
          method: :delete,
          class: "button",
          data: {confirm: "Are you sure?"}
   %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post,@post.comments.build]) do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<br>
<%= f.submit %>
<%end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Photoapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'https://use.fontawesome.com/c6fdab7b37.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
<!-- BEGIN BODY -->
  <body>
    <nav class="nav-extended brown lighten-4">
      <div class="nav-wrapper">
        <div class="center">
          <%= link_to root_path do %>
          <%= image_tag "/P1-AppIcon.png" %>
          <%end %>
        </div>
        <ul class="right">
          <li><%= link_to "New Post",new_post_path%></li>
          <li><%= link_to "Posts", root_path %></li>
          <li><%= link_to "Abouts", about_path %></li>
        </ul>
        <%= link_to new_post_path do%>
        <i class="fa fa-plus-circle"></i>
        <% end %>
      </div>
      <div class="nav-content">
        <span class="nav-title center">PhotoApp</span><br>
        <% if current_user %>
        Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
        <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <div class="card-panel">

<!-- SHOW IF USER IS LOGGED IN -->
<div><%= link_to   new_post_path do %>
  <i class="fa fa-plus-circle f-2" aria-hidden="true"></i>
<%end %></div>

        <% flash.each do |name, msg|  %>
        <%= content_tag(:div, msg, class: "alert") %>
        <% end %>

        <%= yield %>
        </div>
        </div>
        </div>
        <footer class="page-footer brown lighten-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">PhotoApp</h5>
                <p class="grey-text text-lighten-4">Post your photos , commit them to eternity</p>
              </div>

            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Lobsterrific Designs
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">

  <div id="content">
    <h1>Welcome to PhotoApp</h1>
    <p>This app is the newest best photo app on the web
    its bee totally built on ruby on on rails.</p>

  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="card-panel hoverable">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<ul>
<h3>All Posts</h3>
</ul>



    <% @posts.each do |post| %>
      <ul>
        <li><%= image_tag post.image.url(:medium) %></li>
        <li><strong>Title</strong></li>
        <li><%= post.title %></li>
        <li><strong>Content</strong></li>
        <li><%= post.content %></li>
        <li><%= post.created_at.strftime("%B, %d, %Y") %></li>
      </ul>
      <ul>
      <div id="postenddiv">
      <%= link_to 'Show', post %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </ul>
    <% end %>
    <%= will_paginate @posts %>

app/views/posts/new.html.erb
<div id='page_wrapper'>
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="showimg">
<%=image_tag @post.image.url(:large) %>
</div>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p class="date">
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
</p>
<div id="comments">
  <h2>
    <%= @post.comments.count %> comments
  </h2>
  <%= render @post.comments %>
  <h3>Add a comment:</h3>
  <%= render "comments/form"  %>
</div>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>